---
apiVersion: v1
kind: Pod
metadata:
  name: pki-toolbox
  labels:
    app: pki-toolbox
spec:
  containers:
    - name: pki-toolbox
      image: quay.io/kenmoini/pki-toolbox
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
